### ISSUE TITLE
Can't use my connection anymore.

### ISSUE THREAD

**Issue by Potatsdrew** [simeononsecurity/System-Wide-Windows-Ad-Blocker#2]
**Describe the bug**
Once i installed the filter it made my browsers stall for minutes, and give me: "ERR_TIMED_OUT", currently writing from my tablet, please just tell me how to uninstall it!

**To Reproduce**
1. Go to any browser
2. Click on whatever website
3. Wait a bit.
4. See error.

**Expected behavior**
I thought i could use this so that all of my apps have their ads blocked, but as described above, it didn't work..

**Desktop (please complete the following information):**
 - OS: windows 10.
 - Browser Vivaldi/edge.
 - Version i dunno.

**Comment by simeononsecurity** [comment]
It's possible your system didn't quite handle the script correctly. Usually we've noticed this on lower powered machines. If you can please report your system specs and any more details you might could provide.

If you're familiar with the ping and nslookup commands, please tell us if you're able to sucessfully ping 1.1.1.1 and also resolve google.com with the nslookup command. 

If you're still unsuccessful you can revert the changes by copying C:\Windows\System32\drivers\etc\hosts to your desktop, clearing out any entries from the file, and then moving the file back to the folder.

**Comment by SamuelSHrk** [comment]
Same thing happened to me just now, no website will load even with a VPN

**Comment by SamuelSHrk** [comment]
I tried using the hosts rollback to save over the host file but then it said it was used by another process so I guess thos means my computers fucked

**Comment by SamuelSHrk** [comment]
So Im back on the PC thanks to System Restore. Anyways, I dont know where the screenshot went but I did do nslookup on PowerShell for websites like Google and Wikipedia and they both came up saying saying the server was unknown but everything else looked OK.

**Comment by simeononsecurity** [comment]
> I tried using the hosts rollback to save over the host file but then it said it was used by another process so I guess thos means my computers fucked

Yeah that isn't going to be an issue with my script then. That's something else going on on your machine. Possibly anti virus.
