### ISSUE TITLE
Internet runs horribly with this script

### ISSUE THREAD

**Issue by IamAtptModderElectroBoom** [simeononsecurity/System-Wide-Windows-Ad-Blocker#4]
When i applied the script my internet has gotten worse a lot.

Steps to reproduce:

1) apply the script
2) restart

Possible fix:
1) remove the list from the host file
2) restart

**Comment by simeononsecurity** [comment]
> When i applied the script my internet has gotten worse a lot.
> 
> Steps to reproduce:
> 
>     1. apply the script
> 
>     2. restart
> 
> 
> Possible fix:
> 
>     1. remove the list from the host file
> 
>     2. restart

https://github.com/simeononsecurity/System-Wide-Windows-Ad-Blocker#known-issues
