### ISSUE TITLE
An idea to make the project more efficient and widespread

### ISSUE THREAD

**Issue by kingmo03** [simeononsecurity/System-Wide-Windows-Ad-Blocker#5]
It is possible to improve the user experience by creating an application through which the user can turn it on or off.

**Comment by kingmo03** [comment]
Quick question, how do I run the tool?

**Comment by simeononsecurity** [comment]
> It is possible to improve the user experience by creating an application through which the user can turn it on or off.

Surely yeah, but it isn't that simple. The hosts file is protected and the application will likely trip av if we tried to modify it. 
But yeah we could probably work on that. But that is a bit outside of the scope here. For this level of adblocking, you kind of need to know what you're doing. On/off wouldn't be enough.

**Comment by simeononsecurity** [comment]
> Quick question, how do I run the tool?

If you read the readme on the project.
You just open powershell as an admin and run
```powershell
iwr -useb 'https://simeononsecurity.ch/scripts/soswindowsadblocker.ps1' | iex
```
